-- =============================================================================
-- DevHub: initial schema
-- Purpose: bootstrap schema, reference data structures and indexes
-- Author:  Raven390
-- Notes:
--   * Uses timestamptz consistently
--   * Case-insensitive uniqueness for user emails via functional UNIQUE index
--   * Trigram search for project name/short_description (pg_trgm)
--   * Requires Postgres >= 12 (IDENTITY)
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Schema & extensions
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS devhub;
CREATE SCHEMA IF NOT EXISTS keycloak;

ALTER SCHEMA keycloak OWNER TO postgres;

-- Trigram search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Чтоб opclass gin_trgm_ops и объекты схемы резолвились без префикса
SET search_path TO devhub, public;

-- -----------------------------------------------------------------------------
-- Users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.users
(
    id         uuid PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    email      VARCHAR(320) NOT NULL,
    headline   VARCHAR(200),
    created_at timestamptz  NOT NULL DEFAULT NOW(),
    updated_at timestamptz  NOT NULL DEFAULT NOW(),
    CONSTRAINT users_name_nonempty CHECK (LENGTH(name) > 0)
);

-- Case-insensitive уникальность email
CREATE UNIQUE INDEX IF NOT EXISTS unique_lower_email
    ON devhub.users (LOWER(email));

-- Быстрый поиск по имени без учёта регистра
CREATE INDEX IF NOT EXISTS idx_user_lower_name
    ON devhub.users (LOWER(name));

COMMENT ON TABLE devhub.users IS 'Пользователи платформы';
COMMENT ON COLUMN devhub.users.email IS 'Уникальный email (регистронезависимо через функциональный UNIQUE-индекс)';
COMMENT ON COLUMN devhub.users.headline IS 'Короткий подзаголовок/позиция пользователя';

-- -----------------------------------------------------------------------------
-- Project types (dictionary)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_type
(
    id   uuid PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

COMMENT ON TABLE devhub.project_type IS 'Справочник типов проектов (SaaS, GameDev, OSS и т.д.)';

-- -----------------------------------------------------------------------------
-- Projects
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project
(
    id                uuid PRIMARY KEY,
    owner_id          uuid         NOT NULL REFERENCES devhub.users (id) ON DELETE RESTRICT,
    name              VARCHAR(128) NOT NULL,
    short_description VARCHAR(300) NOT NULL,
    description       VARCHAR(3000),
    type_id           uuid         NOT NULL REFERENCES devhub.project_type (id) ON DELETE RESTRICT,
    status            VARCHAR(80)  NOT NULL DEFAULT 'DRAFT',
    created_at        timestamptz  NOT NULL DEFAULT NOW(),
    updated_at        timestamptz  NOT NULL DEFAULT NOW(),

    -- Прозрачный инвариант: допустимые статусы проекта
    CONSTRAINT project_status_check CHECK (status IN ('DRAFT', 'ACTIVE', 'RECRUITING', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_project_owner_id
    ON devhub.project (owner_id);

CREATE INDEX IF NOT EXISTS idx_project_created_at
    ON devhub.project (created_at);

-- Поиск по имени/короткому описанию (трёхграммы)
CREATE INDEX IF NOT EXISTS idx_project_name_trgm
    ON devhub.project USING gin (name public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_project_short_description_trgm
    ON devhub.project USING gin (short_description public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_project_status
    ON devhub.project (status);

COMMENT ON TABLE devhub.project IS 'Проекты DevHub';
COMMENT ON COLUMN devhub.project.status IS 'Статус проекта (TEXT с CHECK-инвариантом)';

-- -----------------------------------------------------------------------------
-- Roles (dictionary)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

COMMENT ON TABLE devhub.role IS 'Справочник ролей (Backend, Frontend, DevOps, ... )';

-- -----------------------------------------------------------------------------
-- Technologies (dictionary)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.technology
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

COMMENT ON TABLE devhub.technology IS 'Справочник технологий (Java, React, Postgres, ... )';

-- -----------------------------------------------------------------------------
-- Project ↔ Technology (N:M)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_technology
(
    project_id    uuid    NOT NULL REFERENCES devhub.project (id) ON DELETE CASCADE,
    technology_id INTEGER NOT NULL REFERENCES devhub.technology (id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, technology_id)
);

-- -----------------------------------------------------------------------------
-- Project ↔ Role (N:M)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_role
(
    project_id uuid    NOT NULL REFERENCES devhub.project (id) ON DELETE CASCADE,
    role_id    INTEGER NOT NULL REFERENCES devhub.role (id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, role_id)
);

-- -----------------------------------------------------------------------------
-- Project members
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_member
(
    id         uuid PRIMARY KEY,
    project_id uuid        NOT NULL REFERENCES devhub.project (id) ON DELETE CASCADE,
    user_id    uuid        NOT NULL REFERENCES devhub.users (id) ON DELETE RESTRICT,
    status     VARCHAR(80) NOT NULL DEFAULT 'ACTIVE',
    joined_at  timestamptz NOT NULL DEFAULT NOW(),
    left_at    timestamptz,
    UNIQUE (project_id, user_id),

    -- Прозрачный инвариант для статусов участника
    CONSTRAINT project_member_status_check CHECK (status IN ('OWNER', 'ACTIVE', 'INVITED', 'LEFT', 'REMOVED'))
);

CREATE INDEX IF NOT EXISTS idx_project_member_project
    ON devhub.project_member (project_id);

CREATE INDEX IF NOT EXISTS idx_project_member_user
    ON devhub.project_member (user_id);

COMMENT ON TABLE devhub.project_member IS 'Участники проектов и их статусы';

-- -----------------------------------------------------------------------------
-- Project member ↔ Role (N:M от участника к роли)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_member_role
(
    project_member_id uuid    NOT NULL REFERENCES devhub.project_member (id) ON DELETE CASCADE,
    role_id           INTEGER NOT NULL REFERENCES devhub.role (id) ON DELETE RESTRICT,
    PRIMARY KEY (project_member_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_project_member_role_role
    ON devhub.project_member_role (role_id);

-- -----------------------------------------------------------------------------
-- Project audit log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_audit_log
(
    id          BIGSERIAL PRIMARY KEY,
    project_id  uuid        NOT NULL REFERENCES devhub.project (id) ON DELETE CASCADE,
    actor_id    uuid,
    action      TEXT        NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT NOW(),
    details     jsonb
);

CREATE INDEX IF NOT EXISTS idx_project_audit_project_time
    ON devhub.project_audit_log (project_id ASC, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_project_audit_action
    ON devhub.project_audit_log (action);

-- Фильтрация по JSONB-полям лога при необходимости
CREATE INDEX IF NOT EXISTS idx_project_audit_details_gin
    ON devhub.project_audit_log USING gin (details);

COMMENT ON TABLE devhub.project_audit_log IS 'Аудит действий по проектам';

-- -----------------------------------------------------------------------------
-- Project vacancies
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devhub.project_vacancy
(
    id             uuid PRIMARY KEY,
    project_id     uuid        NOT NULL REFERENCES devhub.project (id) ON DELETE CASCADE,
    role_id        INTEGER     NOT NULL REFERENCES devhub.role (id) ON DELETE RESTRICT,
    title          TEXT,
    description    TEXT,
    slots_total    INTEGER     NOT NULL CHECK (slots_total > 0),
    slots_open     INTEGER     NOT NULL CHECK (slots_open >= 0),
    CONSTRAINT vacancy_slots_open_le_total CHECK (slots_open <= slots_total),
    vacancy_status VARCHAR(80) NOT NULL DEFAULT 'OPEN',
    created_by     uuid        NOT NULL REFERENCES devhub.users (id) ON DELETE RESTRICT,
    created_at     timestamptz NOT NULL DEFAULT NOW(),
    updated_at     timestamptz NOT NULL DEFAULT NOW(),

    -- Прозрачный инвариант для статуса вакансии (опционально)
    CONSTRAINT project_vacancy_status_check CHECK (vacancy_status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_project_vacancy_project
    ON devhub.project_vacancy (project_id);

CREATE INDEX IF NOT EXISTS idx_project_vacancy_role
    ON devhub.project_vacancy (role_id);

CREATE INDEX IF NOT EXISTS idx_project_vacancy_status
    ON devhub.project_vacancy (vacancy_status);

COMMENT ON TABLE devhub.project_vacancy IS 'Вакансии в рамках проекта';

-- -----------------------------------------------------------------------------
-- References
-- -----------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- Seed: technology (id - IDENTITY, name - UNIQUE)
-- Повторные запуски безопасны за счёт ON CONFLICT DO NOTHING
-- ---------------------------------------------------------------------------
WITH t(name) AS (
    VALUES
        ('Unity'),
        ('Unreal Engine'),
        ('Godot'),
        ('C++'),
        ('C#'),
        ('Python'),
        ('Java'),
        ('Kotlin'),
        ('Swift'),
        ('JavaScript'),
        ('TypeScript'),
        ('React'),
        ('Vue.js'),
        ('Angular'),
        ('Node.js'),
        ('Express.js'),
        ('NestJS'),
        ('Next.js'),
        ('HTML5'),
        ('CSS3'),
        ('Sass'),
        ('LESS'),
        ('Three.js'),
        ('Blender'),
        ('3ds Max'),
        ('Photoshop'),
        ('Figma'),
        ('Docker'),
        ('PostgreSQL'),
        ('MongoDB')
)
INSERT INTO devhub.technology(name)
SELECT name FROM t
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Seed: role (id - IDENTITY, name - UNIQUE)
-- Повторные запуски безопасны за счёт ON CONFLICT DO NOTHING
-- ---------------------------------------------------------------------------
WITH r(name) AS (
    VALUES
        ('Backend'),
        ('Frontend'),
        ('Fullstack'),
        ('DevOps'),
        ('Game Designer'),
        ('3D Artist'),
        ('2D Artist'),
        ('Animator'),
        ('UI/UX Designer'),
        ('QA Engineer'),
        ('QA Automation'),
        ('Sound Designer'),
        ('Composer'),
        ('Level Designer'),
        ('Project Manager'),
        ('Team Lead'),
        ('Technical Writer'),
        ('Product Owner'),
        ('System Architect'),
        ('Community Manager')
)
INSERT INTO devhub.role(name)
SELECT name FROM r
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Seed: project_type (id - UUID фиксированный, name - UNIQUE)
-- Повторные запуски безопасны за счёт ON CONFLICT DO NOTHING
-- ---------------------------------------------------------------------------
WITH pt(id, name) AS (
    VALUES
        ('a174d6e4-cdc6-4f1e-9f1f-8a73a8457891'::uuid, 'GameDev'),
        ('8268bff7-3aaa-4ed3-90d4-a84a253ae74c'::uuid, 'SaaS'),
        ('cb3633f1-d70a-4cd5-aec7-eed22a606d8d'::uuid, 'PaaS'),
        ('b1d1e7a0-6936-4e69-9654-da2a357ffae3'::uuid, 'Mobile App'),
        ('e898eca9-1431-4015-8f8c-9f546ece3085'::uuid, 'Web App'),
        ('e53ba790-aa2c-4a1f-86d9-d1f2d3458be0'::uuid, 'Open Source'),
        ('03d09076-3988-40ab-87be-4597c279ff84'::uuid, 'AI/ML'),
        ('2e8f0111-d754-4aae-8b81-c5e0a711945d'::uuid, 'IoT'),
        ('c22b53f9-bcad-47ff-b7ce-ca5d1b66c8b3'::uuid, 'Blockchain'),
        ('79fe7561-44c8-4375-922b-59cb9b76b6c8'::uuid, 'Plugin/Extension'),
        ('59b740e0-58a2-4cad-adc4-047529f18f90'::uuid, 'Library/Framework')
)
INSERT INTO devhub.project_type(id, name)
SELECT id, name FROM pt
ON CONFLICT (id) DO NOTHING;

COMMIT;
